### PR TITLE
Remove yars parser vulnerability

### PR DESCRIPTION
**Pull request by bidoubiwa**
This PR fixes: #182 and #123 

This has been done by doing the following: 

- Removing all v6.0 dependencies
- Adding all v7.0> dependencies
- Remove `-q` flag that was not compatible with `babel-cli` v7.0 >
- Remove outdated test-coverage that was not used. A newer way of test-coverage compatible with babel v7.0 should be looked for

## Fix failing search

After the update of webpack from 4.* to 5.* some additional parameters are expected for the results we want to have.

**1** in `index.js` we previously used both ES syntax and CommonJs syntax, which resulted in the following error: 
`Uncaught TypeError: "exports" is read-only`

**2** webpack now adds the modules inside the `window` object and because we used a `default` export it was only accessible at `window.docSearchBar.default()`. 
```javascript
// index.js
/* eslint-disable import/no-commonjs */
import docsSearchBar from './src/lib/main';

export default docsSearchBar;
```

 Fortunately webpack has an option to solve this issue: 

> # libraryExport 
> Configure which module or modules will be exposed via the libraryTarget. It is undefined by default, same behaviour will be applied if you set libraryTarget to an empty string e.g. '' it will export the whole (namespace) object. The examples below demonstrate the effect of this configuration when using libraryTarget: 'var'.
>
>The following configurations are supported:
>
> libraryExport: 'default' - The default export of your entry point will be assigned to the library target:
> ```
> // if your entry has a default export of `MyDefaultModule`
> var MyDefaultModule = _entry_return_.default;
>```

### CODE REVIEW

**Review by curquiza — CHANGES_REQUESTED** [review]
Does not work when doing `yarn serve` 😣

```
Uncaught TypeError: "exports" is read-only
```

**Comment by bidoubiwa** [comment]
Mmmh, It is working for me. Did you do `yarn install` to update the dependencies?

**Comment by curquiza** [comment]
Yes I did...

**Review by curquiza — DISMISSED** [review]
👌

**Comment by bidoubiwa** [comment]
bors merge

**Review by curquiza — APPROVED** [review]

**Comment by curquiza** [comment]
you should do bors merge again: it did not work because you dismiss my approval by pushing a new commit.

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
