### PR TITLE
Update version for the next release (v2.3.0)

### PR DESCRIPTION
**Pull request by bidoubiwa**
This version makes this package compatible with Meilisearch v0.29.0 :tada:
Check out the changelog of [Meilisearch v0.29.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.29.0) for more information on the changes.

## 🚀 Enhancements

This change *__may not affect you__*, but in any case, you should check your search queries if you want to keep the same behavior from `v0.28`.

- The `NOT` filter keyword does not have an implicitly `EXIST` operator anymore. Check out for more information: https://github.com/meilisearch/meilisearch/issues/2486

### CODE REVIEW

**Comment by bidoubiwa** [comment]
> Stupid question but why we update a major and not a minor?

To draw their attention to changes in the `filter` behavior! The other SDK's changes their minor as well and consider that change as a breaking change. Nonetheless, we did not want to update docs-searchbar.js to a new major for a change that is not breaking the code.

**Comment by alallema** [comment]
> To draw their attention to changes in the filter behavior! 

Good point!
> we did not want to update docs-searchbar.js to a new major for a change that is not breaking the code.

But it will be updated to a major version here.

**Review by brunoocasali — APPROVED** [review]

**Comment by bidoubiwa** [comment]
> But it will be updated to a major version here.

I think it is [a minor](https://semver.org/).

**Comment by alallema** [comment]
> I think it is [a minor](https://semver.org/).

OH yes!

**Review by alallema — APPROVED** [review]

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
Thanks again for contributing with Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive a small gift from Meilisearch too, don't forget to fill [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
