### PR TITLE
Update version for the next release (v2.4.0)

### PR DESCRIPTION
**Pull request by bidoubiwa**
Update the version of this package

### CODE REVIEW

**Review by alallema — COMMENTED** [review]
The next draft is to v2.4.0 it is ok?

**Comment by bidoubiwa** [comment]
Good point, let me update that

**Review by alallema — APPROVED** [review]
LGTM! 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
Thanks again for contributing with Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive a small gift from Meilisearch too, don't forget to fill [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
