### PR TITLE
Updated Readme (icons and Table Of Content links)

### LINKED ISSUE #654: Fix README table of contents links
In the table of content, the links are broken. To fix it, matching emojis should be added to every title referenced by the table of content.

### PR DESCRIPTION
**Pull request by AyushK-101**
# Pull Request

## Related issue
Fixes #654 

## What does this PR do?
- Updated the icons and fixed the links in table of contents

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)? Yes
- [x] Have you read the contributing guidelines? Yes
- [x] Have you made sure that the title is accurate and descriptive of the changes? Yes

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by proffapt — APPROVED** [review]
Changes are appreciated, and they will solve the issue too

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Comment by bidoubiwa** [comment]
bors merge

**Comment by bidoubiwa** [comment]
Thanks again for contributing with Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive a small gift from Meilisearch too, don't forget to fill [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
